### ISSUE TITLE
カテゴリー＆シリーズ 選択で検索開始

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/web#106]

**Comment by Wansuko-cmd** [comment]
feature/checkbox-activeで実装中
クエリを吐くところまではできたので、あといい感じにお願いします。
編集するファイル：LabeledCheckbox.vue

**Comment by Wansuko-cmd** [comment]
動くところはできたので、スタイル当てます

**Comment by Wansuko-cmd** [comment]
すみません。頑張ってみましたが、自分の実力ではすぐに出来そうにありません

メモ書き
描写時にクエリ取得、ボタンにURLを仕込みつつ、checkedの状態を設定する

**Comment by AAAR-Salmon** [comment]
仕様上どうしてもページ遷移が噛むし（それがなければ実装してもいい）、パフォーマンスやUXを考えるとクリック時に検索は良くないのでは？と思い始めました

**Comment by AAAR-Salmon** [comment]
選択状態の保持だけは実装しようかなと思う

**Comment by Wansuko-cmd** [comment]
選択状態の保持って出来てなかったっけ？

**Comment by Wansuko-cmd** [comment]
まあ確かに押すたびに通信することになるからなぁ・・・

**Comment by smpny7** [comment]
あーなるほどなぁ
でも自分の意見としては、タグをクリックした後に検索ボックス内の虫眼鏡を押しに行くという動作はあまり思いつかないと思うから、ぜひ実装したいかな〜🙇‍♂️
