### ISSUE TITLE
/article?tag=programming のリンク欲しい

### ISSUE THREAD

**Issue by smpny7** [oucrc-org/web#40]

**Comment by smpny7** [comment]
バックエンドの人たちに、「ブログ」テーブルに
- 表示名: (例)プログラミング
- key: (例)programming
の2カラムを用意してもらう必要あり。

**Comment by AAAR-Salmon** [comment]
カテゴリとは別に、複数つけられるタグを用意する感じですか？

**Comment by smpny7** [comment]
ううん、カテゴリーであってる！
