### ISSUE TITLE
部の紹介ページ

### ISSUE THREAD

**Issue by Wansuko-cmd** [oucrc-org/web#88]
ランディングの「部室に何があるの？」のボタンの遷移先の作成

これって新しいページを作って表示する感じであってますか？

**Comment by smpny7** [comment]
そう、そこ何も考えてなかったんよ(笑)
部室紹介の記事へのリンクにするか、1枚のページにするか...
どちらにするかお任せします！w

**Comment by Wansuko-cmd** [comment]
ここまで来たら一枚のページにしてもよさそうですよね・・・
しかし、どういうのを書けばいいのか・・・（部室歴２回）

とりあえず漫画、パソコン、名札くらいが思いつきますね
